# Server
server.servlet.context-path=/api/v1
server.port=8000

# Spring
spring.application.name=PlanifySpring
spring.web.resources.add-mappings=false
logging.level.org.springframework.security=DEBUG

# Database
# [ENV] spring.datasource.url=...
# [ENV] spring.datasource.username=...
# [ENV] spring.datasource.password=...
spring.datasource.driver-class-name=${SPRINT_DATASOURCE_DRIVER_CLASS_NAME}

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
# spring.liquibase.clear-checksums=true

# Redis
# [ENV] spring.data.redis.host=...
# [ENV] spring.data.redis.port=...
# [ENV] spring.data.redis.database=...

# Cache
spring.cache.type=redis

# Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.url=/v3/api-docs

# Mail
spring.mail.host=smtp.yandex.ru
spring.mail.port=465
spring.mail.username=D.S.Murashov@yandex.ru
spring.mail.password=${SERTIVE_EMAIL_APP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true

service.email.from=${SERTIVE_EMAIL_FROM}
