# Server
server.servlet.context-path=/api/v1
server.port=8000

# Application
spring.application.name=PlanifySpring

# Database
# [ENV] spring.datasource.url=...
# [ENV] spring.datasource.username=...
# [ENV] spring.datasource.password=...
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
# spring.liquibase.clear-checksums=true

# Redis
# [ENV] spring.data.redis.host=...
# [ENV] spring.data.redis.port=...
spring.data.redis.database=10

# Cache
spring.cache.type=redis
